# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timestamp',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
